server.port=8085
spring.application.name=currency-conversion

# H2 DB
spring.datasource.url=jdbc:h2:mem:currencydb-dev
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.h2.console.enabled=true

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Tracing
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
