

spring.datasource.url=jdbc:h2:mem:exchange-dev
spring.datasource.username=sa
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.h2.console.enabled=true

spring.sql.init.mode=always

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
